tags:
- name: "post"
  description: "Everything about post"
schemes:
- "http"
paths:
  /post?id=[post id]:
    get:
      tags:
      - "post"
      summary: "get full post info by post id"
      description: "Return full post info"
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "id"
        description: "post id"
        required: true
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/fullPostInfo"
        404:
          description: "Post not found"
  /post/related-to?post-id=[post id]&page=[page number]:
    get:
      tags:
      - "post"
      summary: "get post list related to post id"
      description: "해당 post id 와 같은 장소인 길이가 최대 20인 Post List 를 리턴한다."
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "post-id"
        description: "post id"
        required: true
      - in: "query"
        name: "page"
        description: "page number"
        required: true
      responses:
        200:
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/relatedPost"
        416:
          description: "Range Not Satisfiable : 해당 page 범위에 post 가 없으면 false 를 return"
          schema:
            type: "boolean"
            example: false
        404:
          description: "not found"
definitions:
  fullPostInfo:
    type: "object"
    properties:
      titlePlace:
        type: "string"
      titleCompanion:
        type: "string"
      titleActivity:
        type: "string"
      description:
        type: "string"
      postImageUrls:
        type: "array"
        items:
          type: "string"
      locationName:
        type: "string"
      locationLatitude:
        type: "number"
        format: "float"
      locationAddress:
        type: "string"
      locationPhoneNumber:
        type: "string"
      locationLinkAddress:
        type: "string"
      locationLongitude:
        type: "number"
        format: "float"
      writerNickname:
        type: "string"
      writerImageUrl:
        type: "string"
  relatedPost:
    type: "object"
    properties:
      profileImageURL:
        type: "string"
      titleCompanion:
        type: "string"
      titleActivity:
        type: "string"
      postId:
        type : "number"