tags:
- name: "post"
  description: "Everything about post"
schemes:
- "http"
paths:
  /post?id=$postId:
    get:
      tags:
      - "post"
      summary: "get full post info by post id"
      description: "Return full post info"
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "id"
        description: "post id"
        required: true
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/fullPostInfo"
        404:
          description: "Post not found"
definitions:
  fullPostInfo:
    type: "object"
    properties:
      titlePlace:
        type: "string"
      titleCompanion:
        type: "string"
      titleActivity:
        type: "string"
      description:
        type: "string"
      postImageUrls:
        type: "array"
        items:
          type: "string"
      locationName:
        type: "string"
      locationLatitude:
        type: "number"
        format: "float"
      locationLongitude:
        type: "number"
        format: "float"
      writerNickname:
        type: "string"
      writerImageUrl:
        type: "string"