tags:
- name: "post"
  description: "Everything about post"
- name: "user"
  description: "Everything about user"
schemes:
- "http"
paths:
  /user/info:
    get:
      tags:
      - "user"
      summary: "user 정보 보내기"
      prodeces:
      - "application/json"
      responses:
        200:
          description: "Success"
          schema:
            type: "object"
            properties:
              id:
                type: "number"
              profileImage:
                type: "string"
              email:
                type: "string"
              phone:
                type: "string"
              nickname:
                type: "string"
              description:
                type: "string"
        400:
          description: "Bad Request. JWT 가 유요하지 않음"
        500:
          description: "Internal Server Error"
  /post?page={page number}:
    get:
      tags:
      - "post"
      summary: "각 페이지당 최대 20개의 포스트를 전달한다."
      prodeces:
      - "application/json"
      parameters:
      - in: "query"
        name: "page"
        description: "page number minimum 1"
        required: true
      responses:
        200:
          description: "Success"
          schema:
            type: "object"
            properties:
              hasNextPage:
                type: "boolean"
              posts:
                type: "array"
                items:
                  $ref: "#definitions/postThumbnailInfo"
        204:
          description: "No Contents.\n해당 page의 post가 없다."
        400:
          description: "Bad Request.\n잘못된 page number"
        500:
          description: "Internal Server Error"
  /post/{post id}:
    get:
      tags:
      - "post"
      summary: "get full post info by post id"
      description: "Return full post info"
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "id"
        description: "post id"
        required: true
      responses:
        200:
          description: "Success"
          schema:
              $ref: "#/definitions/fullPostInfo"
        400:
          description: "Bad Request.\npost id가 없다."
        404:
          description: "Not found.\n해당 post id의 post가 없다."
  /post/related-to?postid={post id}&page={page number}:
    get:
      tags:
      - "post"
      summary: "get post list related to post id"
      description: "해당 post id 와 같은 장소인 길이가 최대 20인 Post List 를 리턴한다."
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "post-id"
        description: "post id"
        required: true
      - in: "query"
        name: "page"
        description: "page number"
        required: true
      responses:
        200:
          description: "Ok"
          schema:
            type: "object"
            properties:
              hasNextPage:
                type: "boolean"
              posts:
                type: "array"
                items:
                  $ref: "#/definitions/relatedPost"
        204:
          description: "No Contents.\n해당 장소에 다른 게시글이 없을 때\npage number 가 커서 더이상 글이 없을 때\n존재 하지 않는 post id 일 때"
        400:
          description: "Bad Request.\n요청에 post id or page number 가 없을 때"
definitions:
  fullPostInfo:
    type: "object"
    properties:
      titlePlace:
        type: "string"
      titleCompanion:
        type: "string"
      titleActivity:
        type: "string"
      description:
        type: "string"
      postImageURLs:
        type: "array"
        items:
          type: "string"
      writerNickname:
        type: "string"
      writerImageURL:
        type: "string"
      locationLatitude:
        type: "number"
        format: "float"
      locationLongitude:
        type: "number"
        format: "float"
      locationAddress:
        type: "string"
      locationPhoneNumber:
        type: "string"
      locationLinkAddress:
        type: "string"
      locationExternalLink:
        type: "string"
  relatedPost:
    type: "object"
    properties:
      profileImageURL:
        type: "string"
      titleCompanion:
        type: "string"
      titleActivity:
        type: "string"
      postId:
        type : "number"
  postThumbnailInfo:
    type: "object"
    properties:
      postId:
        type: "number"
      writerImageURL:
        type: "string"
      writerNickname:
        type: "string"
      representativePostImageURL:
        type: "string"
      titlePlace:
        type: "string"
      titleCompanion:
        type: "string"
      titleActivity:
        type: "string"
      description:
        type: "string"